import * as z from "zod/v4";

export const EventName = z.enum([
  "AdditionalContentLoaded",
  "AgentCommand",
  "AgentCreated",
  "ApiInit",
  "AppPaused",
  "AppResumed",
  "AppSuspended",
  "AwardAchievement",
  "BlockBroken",
  "BlockPlaced",
  "BoardTextUpdated",
  "BossKilled",
  "CameraUsed",
  "CauldronUsed",
  "ConfigurationChanged",
  "ConnectionFailed",
  "CraftingSessionCompleted",
  "EndOfDay",
  "EntitySpawned",
  "FileTransmissionCancelled",
  "FileTransmissionCompleted",
  "FileTransmissionStarted",
  "FirstTimeClientOpen",
  "FocusGained",
  "FocusLost",
  "GameSessionComplete",
  "GameSessionStart",
  "HardwareInfo",
  "HasNewContent",
  "ItemAcquired",
  "ItemCrafted",
  "ItemDestroyed",
  "ItemDropped",
  "ItemEnchanted",
  "ItemSmelted",
  "ItemUsed",
  "JoinCanceled",
  "JukeboxUsed",
  "LicenseCensus",
  "MascotCreated",
  "MenuShown",
  "MobInteracted",
  "MobKilled",
  "MultiplayerConnectionStateChanged",
  "MultiplayerRoundEnd",
  "MultiplayerRoundStart",
  "NpcPropertiesUpdated",
  "OptionsUpdated",
  "PerformanceMetrics",
  "PlayerBounced",
  "PlayerDied",
  "PlayerJoin",
  "PlayerLeave",
  "PlayerMessage",
  "PlayerTeleported",
  "PlayerTransform",
  "PlayerTravelled",
  "PortalBuilt",
  "PortalUsed",
  "PortfolioExported",
  "PotionBrewed",
  "PurchaseAttempt",
  "PurchaseResolved",
  "RegionalPopup",
  "RespondedToAcceptContent",
  "ScreenChanged",
  "ScreenHeartbeat",
  "SignInToEdu",
  "SignInToXboxLive",
  "SignOutOfXboxLive",
  "SpecialMobBuilt",
  "StartClient",
  "StartWorld",
  "TextToSpeechToggled",
  "UgcDownloadCompleted",
  "UgcDownloadStarted",
  "UploadSkin",
  "VehicleExited",
  "WorldExported",
  "WorldFilesListed",
  "WorldGenerated",
  "WorldLoaded",
  "WorldUnloaded",
] as const);

export const CompatibilityVersion = z.number().meta({
  description:
    "Number representing the compatibility version. This is always 17104896 as of writing and represents Minecraft version 1.5.0",
});

export const Player = z.strictObject({
  color: z.string().regex(/[0-9a-f]+/g),
  dimension: z.union(
    [
      z.literal(0).meta({ description: "Overworld" }),
      z.literal(1).meta({ description: "Nether" }),
      z.literal(2).meta({ description: "End dimension" }),
    ] as const,
  ),
  id: z.number(),
  name: z.string(),
  position: z.strictObject({
    x: z.number(),
    y: z.number(),
    z: z.number(),
  }).meta({ description: "The position of the player" }),
  type: z.string().meta({ description: 'This is always `"minecraft:player"`' }),
  variant: z.number(),
  yRot: z.number(),
});

