[book]
authors = ["Jonas da Silva"]
language = "en"
src = "src"
title = "MCBE WebSockets"

[output.html]
smart-punctuation = true
additional-css = [
  "./theme/noir.css",
  "./theme/blanc.css",
  "./theme/github-dark.css",
]

[preprocessor.alerts]
